# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 369ff3127c3b11941a8c852de828e6c380d26b5994d706d47ae4424a88ecf557ceb50ef32abcd8d693723bba1e8a7a0a8b77ff7deba189ee3ad92b0835f976fe

test:
  secret_key_base: 278f4150c6deda86fd0cdfa33d09c8dc22b41dc1b651d888da402635df69d7bb4cb286f74851b599a87a79a1b9a1e755627b9c4a5c502a1534fd30c54e061ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
